-- Enable PostGIS for geospatial queries
CREATE EXTENSION IF NOT EXISTS postgis;

-- -----------------------------------------------------
-- Enums
-- -----------------------------------------------------
CREATE TYPE court_status AS ENUM ('OPEN', 'BUSY', 'FULL', 'MAINTENANCE');

-- -----------------------------------------------------
-- Profiles Table (Public User Data)
-- -----------------------------------------------------
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE,
  
  CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone."
  ON profiles FOR SELECT
  USING (true);

CREATE POLICY "Users can insert their own profile."
  ON profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile."
  ON profiles FOR UPDATE
  USING (auth.uid() = id);

-- -----------------------------------------------------
-- Courts Table
-- -----------------------------------------------------
CREATE TABLE courts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  location GEOGRAPHY(POINT) NOT NULL,
  borough TEXT NOT NULL,
  surface_type TEXT,
  current_status court_status DEFAULT 'OPEN',
  status_updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE courts ENABLE ROW LEVEL SECURITY;

-- Courts Policies
CREATE POLICY "Courts are viewable by everyone."
  ON courts FOR SELECT
  USING (true);

-- Only service role or admins can update courts directly via API
-- (For user reports affecting status, we'll use a Database Function later)

-- -----------------------------------------------------
-- Check-ins Table
-- -----------------------------------------------------
CREATE TABLE checkins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  court_id BIGINT REFERENCES courts(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Enable RLS
ALTER TABLE checkins ENABLE ROW LEVEL SECURITY;

-- Checkins Policies
CREATE POLICY "Checkins are viewable by everyone."
  ON checkins FOR SELECT
  USING (true);

CREATE POLICY "Users can check in themselves."
  ON checkins FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Optional: Users can delete their own check-in (check-out)
CREATE POLICY "Users can delete their own check-in."
  ON checkins FOR DELETE
  USING (auth.uid() = user_id);

-- -----------------------------------------------------
-- Reports Table (Crowdsourced Status)
-- -----------------------------------------------------
CREATE TABLE reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  court_id BIGINT REFERENCES courts(id) ON DELETE CASCADE NOT NULL,
  status_reported court_status NOT NULL,
  proof_image_url TEXT,
  location_verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

-- Reports Policies
CREATE POLICY "Reports are viewable by everyone."
  ON reports FOR SELECT
  USING (true);

CREATE POLICY "Users can submit reports."
  ON reports FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- -----------------------------------------------------
-- Indexes
-- -----------------------------------------------------
-- Geospatial Index for fast "nearby" queries
CREATE INDEX courts_location_idx ON courts USING GIST (location);

-- Foreign Key Indexes for join performance
CREATE INDEX checkins_court_id_idx ON checkins(court_id);
CREATE INDEX checkins_user_id_idx ON checkins(user_id);
CREATE INDEX reports_court_id_idx ON reports(court_id);
CREATE INDEX reports_user_id_idx ON reports(user_id);

-- -----------------------------------------------------
-- Helper: Handle New User Creation (Optional but recommended)
-- -----------------------------------------------------
-- This trigger automatically creates a profile entry when a new user signs up via Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
