-- Enable PostGIS
CREATE EXTENSION IF NOT EXISTS postgis;

-- -----------------------------------------------------
-- Reports Table (Crowdsourced Status)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  court_id BIGINT, -- Assuming static court IDs for now, or FK if using DB courts
  status_reported TEXT CHECK (status_reported IN ('OPEN', 'BUSY', 'FULL', 'CLOSED')),
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  location_verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Everyone can read reports"
  ON public.reports FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can submit reports"
  ON public.reports FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- -----------------------------------------------------
-- Function: Submit Report with Geofence Check
-- -----------------------------------------------------
CREATE OR REPLACE FUNCTION public.submit_report(
  p_court_id BIGINT,
  p_status TEXT,
  p_lat DOUBLE PRECISION,
  p_long DOUBLE PRECISION,
  p_court_lat DOUBLE PRECISION,
  p_court_long DOUBLE PRECISION
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_distance DOUBLE PRECISION;
  v_report_id BIGINT;
BEGIN
  -- Calculate distance in meters using PostGIS
  -- Note: We construct geometry points from the coordinates
  v_distance := ST_Distance(
    ST_SetSRID(ST_MakePoint(p_long, p_lat), 4326)::geography,
    ST_SetSRID(ST_MakePoint(p_court_long, p_court_lat), 4326)::geography
  );

  -- Check if within 100 meters
  IF v_distance > 100 THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'You are too far from the court (' || round(v_distance::numeric, 0) || 'm). Must be within 100m.'
    );
  END IF;

  -- Insert the report
  INSERT INTO public.reports (user_id, court_id, status_reported, latitude, longitude, location_verified)
  VALUES (auth.uid(), p_court_id, p_status, p_lat, p_long, true)
  RETURNING id INTO v_report_id;

  RETURN jsonb_build_object(
    'success', true,
    'message', 'Report submitted successfully.',
    'report_id', v_report_id,
    'distance', v_distance
  );
END;
$$;
