-- -----------------------------------------------------
-- Social Enhancements
-- -----------------------------------------------------

-- 1. Add Beacon to Checkins
ALTER TABLE public.checkins 
ADD COLUMN IF NOT EXISTS looking_for_game BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS skill_level TEXT;

-- 2. Create Subscriptions Table
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  court_id BIGINT REFERENCES courts(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, court_id)
);

-- Enable RLS for Subscriptions
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can see own subscriptions"
  ON public.subscriptions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can subscribe themselves"
  ON public.subscriptions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can unsubscribe themselves"
  ON public.subscriptions FOR DELETE
  USING (auth.uid() = user_id);


-- 3. Update Check-In Function to support Beacon
CREATE OR REPLACE FUNCTION public.check_in(
  p_court_id BIGINT,
  p_status checkin_status,
  p_party_size INTEGER DEFAULT 1,
  p_looking_for_game BOOLEAN DEFAULT FALSE
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_checkin_id BIGINT;
BEGIN
  -- Remove existing check-in
  DELETE FROM public.checkins WHERE user_id = auth.uid();

  -- Insert new check-in with beacon support
  INSERT INTO public.checkins (
    user_id, 
    court_id, 
    status, 
    party_size, 
    looking_for_game,
    expires_at
  )
  VALUES (
    auth.uid(), 
    p_court_id, 
    p_status, 
    p_party_size, 
    p_looking_for_game,
    NOW() + INTERVAL '2 hours'
  )
  RETURNING id INTO v_checkin_id;

  RETURN jsonb_build_object(
    'success', true,
    'message', 'Checked in successfully.',
    'checkin_id', v_checkin_id
  );
END;
$$;

-- 4. Update Queue Fetcher to include Beacon info
CREATE OR REPLACE FUNCTION public.get_court_queue(p_court_id BIGINT)
RETURNS TABLE (
  username TEXT,
  avatar_url TEXT,
  status checkin_status,
  party_size INTEGER,
  looking_for_game BOOLEAN,
  created_at TIMESTAMP WITH TIME ZONE
)
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT 
    p.username,
    p.avatar_url,
    c.status,
    c.party_size,
    c.looking_for_game,
    c.created_at
  FROM public.checkins c
  JOIN public.profiles p ON c.user_id = p.id
  WHERE c.court_id = p_court_id
  ORDER BY c.created_at ASC;
$$;
